### ISSUE TITLE
Cannot compile on io.js 1.5.1

### ISSUE THREAD

**Issue by martinmicunda** [Voxer/sse4_crc32#22]
```bash
> sse4_crc32@2.1.2 install /home/vagrant/api/node_modules/nsqjs/node_modules/snappystream/node_modules/sse4_crc32
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/vagrant/api/node_modules/nsqjs/node_modules/snappystream/node_modules/sse4_crc32/build'
  CXX(target) Release/obj.target/sse4_crc32/src/sse4_crc32.o
make: g++: Command not found
make: *** [Release/obj.target/sse4_crc32/src/sse4_crc32.o] Error 127
make: Leaving directory `/home/vagrant/api/node_modules/nsqjs/node_modules/snappystream/node_modules/sse4_crc32/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/iojs-v1.5.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Linux 3.13.0-30-generic
gyp ERR! command "node" "/usr/local/lib/iojs-v1.5.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/api/node_modules/nsqjs/node_modules/snappystream/node_modules/sse4_crc32
gyp ERR! node -v v1.5.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-30-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v1.5.1
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
```

**Comment by bahamas10** [comment]
```
make: g++: Command not found
```

it seems like this may be the problem

**Comment by martinmicunda** [comment]
thanks that's fixed my problem
