### ISSUE TITLE
Fail to build with iojs v2.0.1 and npm v2.9.1

### ISSUE THREAD

**Issue by dmtrs** [Voxer/sse4_crc32#30]
I am using `nvm` to manage node versions and althought the code is build with `v0.12` of node. I can not understand why it is not possible with `v2.0.1` which is `iojs`. Here is the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/io.js/v2.0.1/bin/iojs',
1 verbose cli   '/home/user/.nvm/versions/io.js/v2.0.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   '.' ]
2 info using npm@2.9.1
3 info using node@v2.0.1
4 verbose readDependencies loading dependencies from /home/user/code/sse4_crc32/package.json
5 verbose install where, deps [ '/home/user/code/sse4_crc32',
5 verbose install   [ 'bindings', 'nan', 'node-gyp', 'mocha', 'chai', 'crc32' ] ]
6 verbose install where, peers [ '/home/user/code/sse4_crc32', [] ]
7 verbose installManyTop reading for lifecycle /home/user/code/sse4_crc32/package.json
8 info preinstall sse4_crc32@3.1.2
9 verbose installManyTop reading scoped package data from /home/user/code/sse4_crc32/node_modules/bindings/package.json
10 verbose installManyTop reading scoped package data from /home/user/code/sse4_crc32/node_modules/chai/package.json
11 verbose installManyTop reading scoped package data from /home/user/code/sse4_crc32/node_modules/crc32/package.json
12 verbose installManyTop reading scoped package data from /home/user/code/sse4_crc32/node_modules/mocha/package.json
13 verbose installManyTop reading scoped package data from /home/user/code/sse4_crc32/node_modules/nan/package.json
14 verbose installManyTop reading scoped package data from /home/user/code/sse4_crc32/node_modules/node-gyp/package.json
15 verbose readDependencies loading dependencies from /home/user/code/sse4_crc32/package.json
16 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/bindings/package.json
17 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/chai/package.json
18 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/crc32/package.json
19 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/mocha/package.json
20 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/nan/package.json
21 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/node-gyp/package.json
22 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/.bin/crc32/package.json
23 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/.bin/mocha/package.json
24 verbose targetResolver reading package data from /home/user/code/sse4_crc32/node_modules/.bin/node-gyp/package.json
25 verbose already installed skipping crc32@>=0.2.1 /home/user/code/sse4_crc32
26 verbose already installed skipping bindings@~1.2.1 /home/user/code/sse4_crc32
27 verbose already installed skipping node-gyp@^1.0.2 /home/user/code/sse4_crc32
28 verbose already installed skipping nan@^1.7.0 /home/user/code/sse4_crc32
29 verbose already installed skipping mocha@>=2.1.0 /home/user/code/sse4_crc32
30 verbose already installed skipping chai@>=2.0.0 /home/user/code/sse4_crc32
31 silly install resolved []
32 info build /home/user/code/sse4_crc32
33 info linkStuff sse4_crc32@3.1.2
34 silly linkStuff sse4_crc32@3.1.2 has /home/user/code as its parent node_modules
35 verbose linkBins sse4_crc32@3.1.2
36 verbose linkMans sse4_crc32@3.1.2
37 verbose rebuildBundles sse4_crc32@3.1.2
38 verbose rebuildBundles [ '.bin', 'bindings', 'chai', 'crc32', 'mocha', 'nan', 'node-gyp' ]
39 info install sse4_crc32@3.1.2
40 verbose unsafe-perm in lifecycle true
41 info sse4_crc32@3.1.2 Failed to exec install script
42 verbose stack Error: sse4_crc32@3.1.2 install: `node-gyp rebuild`
42 verbose stack Exit status 1
42 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
42 verbose stack     at emitTwo (events.js:87:13)
42 verbose stack     at EventEmitter.emit (events.js:169:7)
42 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
42 verbose stack     at emitTwo (events.js:87:13)
42 verbose stack     at ChildProcess.emit (events.js:169:7)
42 verbose stack     at maybeClose (child_process.js:953:16)
42 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
43 verbose pkgid sse4_crc32@3.1.2
44 verbose cwd /home/user/code/sse4_crc32
45 error Darwin 14.0.0
46 error argv "/home/user/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/user/.nvm/versions/io.js/v2.0.1/bin/npm" "install" "."
47 error node v2.0.1
48 error npm  v2.9.1
49 error code ELIFECYCLE
50 error sse4_crc32@3.1.2 install: `node-gyp rebuild`
50 error Exit status 1
51 error Failed at the sse4_crc32@3.1.2 install script 'node-gyp rebuild'.
51 error This is most likely a problem with the sse4_crc32 package,
51 error not with npm itself.
51 error Tell the author that this fails on your system:
51 error     node-gyp rebuild
51 error You can get their info via:
51 error     npm owner ls sse4_crc32
51 error There is likely additional logging output above.
52 verbose exit [ 1, true ]
```

**Comment by anandsuresh** [comment]
@dmtrs  Can you please send me more information about the platform on which you are seeing this?

**Comment by dmtrs** [comment]
Moved to `iojs v.2.1.0` and system update resolved the issue
