### ISSUE TITLE
Module did not self-register when require(gcloud)

### ISSUE THREAD

**Issue by mziccard** [Voxer/sse4_crc32#40]
I am experiencing the infamous problem already mentioned in https://github.com/GoogleCloudPlatform/gcloud-node/issues/681.
To reproduce the error:
package.json:
```javascript
{
  "name": "test",
  "dependencies": {
    "gcloud": "^0.20.0"
  }
```
test.js:
```javascript
var gcloud = require('gcloud');
```
node version: 0.12.7
npm version: 2.11.3
linux kernel: 3.14.22-100.fc19.x86_64
gcc: 4.8.3

Compilation (`npm install`) goes just fine:
```
npm WARN package.json test@ No description
npm WARN package.json test@ No repository field.
npm WARN package.json test@ No README data
npm WARN package.json test@ No license field.
 
> sse4_crc32@3.4.0 install /home/mziccard/Desktop/test/node_modules/gcloud/node_modules/sse4_crc32
> node-gyp rebuild

make: Entering directory `/home/mziccard/Desktop/test/node_modules/gcloud/node_modules/sse4_crc32/build'
  CXX(target) Release/obj.target/sse4_crc32/src/sse4_crc32.o
  SOLINK_MODULE(target) Release/obj.target/sse4_crc32.node
  COPY Release/sse4_crc32.node
make: Leaving directory `/home/mziccard/Desktop/test/node_modules/gcloud/node_modules/sse4_crc32/build'
gcloud@0.20.0 node_modules/gcloud
├── propprop@0.3.0
├── prop-assign@1.0.0
├── arrify@1.0.0
├── string-format-obj@1.0.1
├── methmeth@1.1.0
├── buffer-equal@0.0.1
├── extend@2.0.1
├── is@3.0.1
├── dns-zonefile@0.1.9
├── node-uuid@1.4.3
├── stream-forward@3.0.0 (stubs@2.0.0)
├── stream-events@1.0.1 (stubs@1.1.2)
├── async@0.9.2
├── split-array-stream@1.0.0 (is-stream-ended@0.1.0, async@1.4.2)
├── once@1.3.2 (wrappy@1.0.1)
├── retry-request@1.2.1 (stream-cache@0.0.2)
├── concat-stream@1.5.0 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.2)
├── duplexify@3.4.2 (end-of-stream@1.0.0, readable-stream@2.0.2)
├── mime-types@2.1.5 (mime-db@1.17.0)
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
├── configstore@1.2.1 (os-tmpdir@1.0.1, object-assign@3.0.0, graceful-fs@4.1.2, xdg-basedir@2.0.0, uuid@2.0.1, osenv@0.1.3, write-file-atomic@1.1.2, mkdirp@0.5.1)
├── gce-images@0.1.0 (object-assign@3.0.0, google-auto-auth@0.1.1, async@1.4.2, got@4.1.1)
├── request@2.61.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, qs@4.0.0, form-data@1.0.0-rc3, combined-stream@1.0.5, http-signature@0.11.0, bl@1.0.0, tough-cookie@2.0.0, hawk@3.1.0, har-validator@1.8.0)
├── sse4_crc32@3.4.0 (bindings@1.2.1, nan@1.9.0)
├── google-auth-library@0.9.6 (lodash.noop@3.0.0, string-template@0.2.1, request@2.51.0, gtoken@1.1.2, jws@3.0.0)
└── protobufjs@3.8.2 (ascli@0.3.0, bytebuffer@3.5.5)
```
Executing the test with `node test.js` causes the error:
```
/home/mziccard/Desktop/test/node_modules/gcloud/node_modules/sse4_crc32/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/mziccard/Desktop/test/node_modules/gcloud/node_modules/sse4_crc32/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/mziccard/Desktop/test/node_modules/gcloud/node_modules/sse4_crc32/sse4_crc32.js:8:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
The test project is created from scratch, first `npm install` is run, followed by `node test.js`, no version changes or upgrades in the middle (`npm rebuild` and `rm -rf node_modules` are of no use).
Oddly enough, with an older node version (0.10.33) the test runs smoothly. Any idea? This problem might not even be related with your module but better check first:)

**Comment by anandsuresh** [comment]
@mziccard No idea. Haven't had a chance to test this stuff on Node 12 yet. But I have seen a bunch of people run into this error on different NPM modules when running on node 0.12.x.

**Comment by mziccard** [comment]
@anandsuresh Thanks for the fast feedback. I noticed a growing number of such errors as well and today I stumbled upon it myself. If you ever find out anything or decide to test your module with Node 12 please keep me posted.

**Comment by anandsuresh** [comment]
For sure. I have bunch of stuff on my plate at the moment, but when I do get a chance I'd like to try this out myself.

**Comment by mziccard** [comment]
I realized that I was unknowingly using node-pyp built for a previous version of node (0.10.33). Since I had `/usr/bin/node` pointing to node version `0.10.33`, executing `path/to/0.12.7/npm install -g node-pyp`  triggered no node-pyp rebuild. Updating `/usr/bin/node` to point to node version `0.12.7` fixed this non-existing issue.  

Your module works like a charm in node 0.12.7 :smile:

**Comment by anandsuresh** [comment]
Sweet. Glad it worked out in the end.
